### ISSUE TITLE
[suggestion] menu shortcuts should reflect final string format

### ISSUE THREAD

**Issue by jareis** [adamwalzer/string-converter#1]
Hello,

Thanks for taking the time to make this. I only have one ux suggestion.

Is easier to understand the text manipulator action, if it reflects the output format
ex. 

> Text Manipulator: kebabCase -> Text Manipulator: kebab-case
> Text Manipulator: snakeCase -> Text Manipulator: snake_case

(...)

**Comment by adamwalzer** [comment]
@jareis sorry for the super late reply but the newest version of this extension should resolve this
