### ISSUE TITLE
Add global shortcut to display a menu of options

### ISSUE THREAD

**Issue by FatehAK** [adamwalzer/string-converter#3]
Is it possible to add a single shortcut that triggers a menu that shows the all the options. Currently a single shortcut is bounded to a single option. Having one shortcut that displays all the options available in a menu should be useful so the user can use arrow keys to select from the menu.

**Comment by adamwalzer** [comment]
The newest version of this extension I just published now has a command showTextManipulatorMenu that you can create a shortcut for using keyboard shortcuts menu
