### ISSUE TITLE
space case doesn't handle multiple separations

### ISSUE THREAD

**Issue by shanemgrey** [adamwalzer/string-converter#4]
To reproduce:

1. Select this string: change_in_income
2. Run Text Manipulator: spaceCase

Expected Result: change in income

Actual Result: change in-income

Only the first separator seems to be handled as expected in the transformation.  The others are transformed to the dash "-" character

This also seems to be happening in the pathCase option.  And possibly others.

**Comment by adamwalzer** [comment]
Thanks for the issue. This should be fixed in the in the version I just published now
